version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3333:3333
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379